server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/cheanna/IdeaProjects/ctype/chatbot-hivey-backend-spring-MSA/git-local-repo